### ISSUE TITLE
Cypress Error when running `yarn test`

### ISSUE THREAD

**Issue by JackEdwardLyons** [chrisvfritz/vue-enterprise-boilerplate#168] opened 2019-09-02 20:32 UTC
I'm sure there's a super simple fix to this, but can you please explain why when I run `npm test / yarn test` I get this Cypress error?
I've tried "booting" my server before, but still the error occurs. What steps do I need to take to resolve this? Do I need to explicitly set the baseUrl in an .env file or sth like that?

```
Cypress could not verify that the server set as your `baseUrl` is running:

  > http://localhost:8080/

Your tests likely make requests to this `baseUrl` and these tests will fail if you don't boot your server.

Please start this server and then run Cypress again.
```

Thanks in advance!

**Comment by chrisvfritz** [comment] 2019-10-02 18:05
Hm, running `yarn test` should automatically boot your dev server. I haven't seen this error personally, but it's possible that the problem is due to a bug either in Cypress, Vue CLI, or Webpack which might now be fixed as I updated dependencies recently. Can you confirm that this still happens for you on a fresh project?

**Comment by chrisvfritz** [comment] 2019-10-10 05:14
Closing for now, but open to reopening if someone is able to reproduce this. 🙂

**Closed by chrisvfritz** 2019-10-10 05:14 UTC
Labels: bug, needs repro
